export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/reg'
export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const TICKET_ROUTE = '/ticket'